name: Metadata Image Build and Push

env:
  IMAGE_NAME: ghcr.io/justereseau/satisfactory-metadata
  
on:
  push:
    branches: ["main"]
    paths:
      - satisfactory-metadata/**
      - .github/workflows/build-metadata-images.yml
  pull_request:
    branches: ["main"]

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./satisfactory-metadata
          platforms: linux/amd64
          push: true
          tags: "${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ github.sha }}"
