name: Exporter Binary Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - README.md
      - LICENSE
      - .github/workflows/container.yml
      - Dockerfile
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [linux, windows, darwin]
        GOARCH: [amd64, arm64]
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build for ${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        working-directory: ./satisfactory-exporter
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
        run: go build -o satisfactory-exporter -ldflags "-s -w" main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: satisfactory-exporter-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: ./satisfactory-exporter/satisfactory-exporter
