name: Deploy Images to GHCR

env:
  IMAGE_NAME: ghcr.io/lucasmaurice/satisfactory-metrics

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64,linux/arm/v7 \
            --file ./Dockerfile \
            --build-arg COMMIT_HASH=${{ github.sha }} \
            --tag ${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --push .
